export const ROLES = Object.freeze({
  PLATFORM_OWNER: 'platform_owner',
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  TEACHER: 'teacher',
  STUDENT: 'student',
  PARENT: 'parent',
});

export const ROLE_HIERARCHY = Object.freeze({
  [ROLES.PLATFORM_OWNER]: 100,
  [ROLES.SUPER_ADMIN]: 90,
  [ROLES.ADMIN]: 70,
  [ROLES.TEACHER]: 50,
  [ROLES.STUDENT]: 30,
  [ROLES.PARENT]: 10,
});

export const PERMISSIONS = Object.freeze({
  MANAGE_INSTITUTIONS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN],
  MANAGE_USERS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_EXAMS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER],
  MANAGE_QUESTIONS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER],
  START_EXAM: [ROLES.STUDENT],
  SUBMIT_EXAM: [ROLES.STUDENT],
  VIEW_OWN_RESULT: [ROLES.STUDENT, ROLES.PARENT],
  VIEW_ALL_RESULTS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER],
  RELEASE_RESULTS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER],
  MANAGE_PAYMENTS: [ROLES.SUPER_ADMIN],
  VIEW_ANALYTICS: [ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.TEACHER],
  VIEW_CHILD_RESULTS: [ROLES.PARENT],
});
