import { getPrisma } from '../../infrastructure/database/prisma.js';
import { generatePdf } from '../../infrastructure/pdf/pdf.client.js';
import { NotFoundError } from '../../types/errors.js';

function buildQuestionPaperHtml(exam, questions) {
  const questionRows = questions.map((q, i) => `
    <tr>
      <td class="num">${i + 1}.</td>
      <td class="qtext">${q.questionText}</td>
      <td class="marks">${q.marks}</td>
    </tr>
  `).join('');

  const optionsList = questions.map((q) => {
    const opts = Object.entries(q.options).map(([label, text]) => `<li>${label}. ${text}</li>`).join('');
    return `<div class="opts"><strong>Q${q.orderIndex}:</strong> <ol class="opt-list">${opts}</ol></div>`;
  }).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body { font-family: serif; font-size: 12pt; line-height: 1.6; }
  .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
  .header h1 { font-size: 18pt; margin: 0; }
  .header p { margin: 2px 0; font-size: 11pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 15px; }
  th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; }
  th { background: #eee; font-weight: bold; }
  .num { width: 40px; text-align: center; }
  .marks { width: 60px; text-align: center; }
  .opts { margin: 10px 0 15px 0; padding-left: 30px; }
  .opt-list { list-style: none; padding: 0; }
  .opt-list li { padding: 2px 0; }
  .footer { margin-top: 30px; text-align: center; font-size: 10pt; color: #666; }
  .instructions { margin: 15px 0; padding: 10px; border: 1px solid #ccc; font-size: 11pt; }
</style></head><body>
<div class="header">
  <h1>${exam.title}</h1>
  ${exam.description ? `<p>${exam.description}</p>` : ''}
  <p>Duration: ${exam.durationMinutes} minutes | Total Marks: ${exam.totalMarks}</p>
</div>
<div class="instructions">
  <strong>Instructions:</strong>
  <ol>
    <li>This question paper contains ${questions.length} questions.</li>
    <li>Each question carries indicated marks.</li>
    <li>Mark your answers on the OMR sheet provided separately.</li>
    <li>${exam.negativeMarking ? 'There is negative marking for wrong answers.' : 'No negative marking for wrong answers.'}</li>
  </ol>
</div>
<table>
  <thead><tr><th>Q.No</th><th>Question</th><th>Marks</th></tr></thead>
  <tbody>${questionRows}</tbody>
</table>
${optionsList}
<div class="footer">Generated by EduOMR — ${new Date().toLocaleDateString()}</div>
</body></html>`;
}

export async function generateQuestionPaperPdf(tenantId, examId) {
  const prisma = getPrisma();
  const exam = await prisma.exam.findFirst({
    where: { id: examId, tenantId, deletedAt: null },
  });
  if (!exam) throw new NotFoundError('Exam not found');

  const questions = await prisma.question.findMany({
    where: { examId, tenantId },
    orderBy: { orderIndex: 'asc' },
  });

  const html = buildQuestionPaperHtml(exam, questions);
  return generatePdf(html, { preferCSSPageSize: true });
}
